services:

  mysql:
    image: mysql:8.0
    container_name: ocare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ocare_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: ocare-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: ocare-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    container_name: ocare-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper